# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.optika.dv:587
mail_admin: admin@optika.dv
mail_hostname: optika.dv
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
